package com.thefork.challenge.api

data class UserFull(
    val id: String,
    val title: String,
    val firstName: String,
    val lastName: String,
    val gender: String,
    val email: String,
    val dateOfBirth: String,
    val registerDate: String,
    val phone: String,
    val picture: String,
    val location: Location
)

data class Location(
    val street: String,
    val city: String,
    val state: String,
    val country: String,
    val timezone: String
)

//Full user data returned by id.
//{
//    id: string(autogenerated)
//    title: string("mr", "ms", "mrs", "miss", "dr", "")
//    firstName: string(length: 2-50)
//    lastName: string(length: 2-50)
//    gender: string("male", "female", "other", "")
//    email: string(email)
//    dateOfBirth: string(ISO Date - value: 1/1/1900 - now)
//    registerDate: string(autogenerated)
//    phone: string(phone number - any format)
//    picture: string(url)
//    location: object(Location)
//}