package com.thefork.challenge.api

import com.thefork.challenge.domain.User
import com.thefork.challenge.domain.UserLocation

data class UserFull(
    val id: String,
    val title: String,
    val firstName: String,
    val lastName: String,
    val gender: String,
    val email: String,
    val dateOfBirth: String,
    val registerDate: String,
    val phone: String,
    val picture: String,
    val location: UserFullLocation
)

data class UserFullLocation(
    val street: String,
    val city: String,
    val state: String,
    val country: String,
    val timezone: String
)

fun UserFull.toDomain(): User {
    return User(
        id = id,
        title = title,
        firstName = firstName,
        lastName = lastName,
        gender = gender,
        email = email,
        dateOfBirth = dateOfBirth,
        registerDate = registerDate,
        phone = phone,
        picture = picture,
        location = location.toDomain()
    )
}

fun UserFullLocation.toDomain(): UserLocation {
    return UserLocation(
        street = street,
        city = city,
        state = state,
        country = country,
        timezone = timezone
    )
}

//Full user data returned by id.
//{
//    id: string(autogenerated)
//    title: string("mr", "ms", "mrs", "miss", "dr", "")
//    firstName: string(length: 2-50)
//    lastName: string(length: 2-50)
//    gender: string("male", "female", "other", "")
//    email: string(email)
//    dateOfBirth: string(ISO Date - value: 1/1/1900 - now)
//    registerDate: string(autogenerated)
//    phone: string(phone number - any format)
//    picture: string(url)
//    location: object(Location)
//}